name: deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - uses: actions/checkout@v2

    - name: Set version
      id: set_version
      run: |
        Invoke-WebRequest -Uri https://github.com/jasondavis303/TimestampVersion/releases/latest/download/tsv.exe -OutFile tsv.exe
        .\tsv.exe --xml-files MyNet\MyNet.csproj --set-ov --verbose
      
    - name: Build
      run: |
        dotnet publish -c release -o publish
        Invoke-WebRequest -Uri https://github.com/jasondavis303/SelfUpdatingApps/releases/latest/download/suag.exe -OutFile suag.exe
        .\suag.exe build --name MyNet --app-id "3DD9B4C4-6090-4A95-B9DB-5C9BF731A704" --app-version ${{ steps.set_version.outputs.TIMESTAMP_VERSION }} --source-exe publish\MyNet.exe --target-dir upload --depo https://s3.us-west-1.wasabisys.com/jd-media/suadepo/ --no-gui
        
    - name: Upload
      run: |
        Invoke-WebRequest -Uri https://github.com/jasondavis303/s3u/releases/latest/download/s3u.exe -OutFile s3u.exe
        .\s3u.exe --endpoint ${{ secrets.S3_ENDPOINT }} --access-key ${{ secrets.S3_KEY_ID }} --access-secret ${{ secrets.S3_SECRET }} --source upload --bucket ${{ secrets.S3_BUCKET }} --target suadepo --overwrite --verbose
