name: deploy

on:
  push:
    branches: [ master ]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: jasondavis303/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.S3_KEY_ID }}
          aws_secret_access_key: ${{ secrets.S3_SECRET }}
          aws_bucket: ${{ secrets.S3_BUCKET }}
          source_dir: 'MyNet/bin/publish'
          destination_dir: 'test/upload/key'