name: deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - run: dotnet restore

    - uses: microsoft/setup-msbuild@v1       

    - run: msbuild MyNet.sln /t:Publish /p:Configuration=Release /p:PublishProfile=ClickOnceProfile.pubxml

    - uses: jasondavis303/upload-s3-action@v1.0.2
      with:
        aws_key_id: ${{ secrets.S3_KEY_ID }}
        aws_secret_access_key: ${{ secrets.S3_SECRET }}
        aws_bucket: ${{ secrets.S3_BUCKET }}
        source_dir: 'MyNet/bin/Release/net5.0-windows/app.publish'
        destination_dir: 'test/upload/key'